### ISSUE TITLE
#<TypeError: no implicit conversion of nil into String>

### ISSUE THREAD

**Issue by erisco** [bitrise-io/steps-xamarin-test-cloud-for-android#12]
Fails on version 1.1.0, does not fail on version 1.0.1

```
#<TypeError: no implicit conversion of nil into String>
--- Stack trace: ---
["/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/analyzer.rb:192:in `include?'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/analyzer.rb:192:in `block (2 levels) in build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/analyzer.rb:190:in `each'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/analyzer.rb:190:in `block in build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/analyzer.rb:165:in `each'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/analyzer.rb:165:in `build_test_commands'", "/private/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/xamarin-builder/builder.rb:53:in `build_test'", "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise764798769/step_src/step.rb:104:in `<main>'"]
```

**Comment by godrei** [comment]
Hi @erisco ,
new version ([v.1.1.1](https://github.com/bitrise-steplib/steps-xamarin-test-cloud-for-android/releases/tag/1.1.1)) is out, it should fix this issue.
